"""
Example Selenium Test Script
Generated by QA Agent System

This is a sample test script to demonstrate the structure and quality
of scripts generated by the system.

Test Case: Validate discount code SAVE15 application
"""

import unittest
import time
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


class TestDiscountCodeValidation(unittest.TestCase):
    """Test suite for discount code validation"""
    
    @classmethod
    def setUpClass(cls):
        """Set up test fixtures before running tests"""
        # Set up Chrome WebDriver
        service = Service(ChromeDriverManager().install())
        cls.driver = webdriver.Chrome(service=service)
        cls.driver.maximize_window()
        cls.wait = WebDriverWait(cls.driver, 10)
        
        # Get the absolute path to the HTML file
        current_dir = os.path.dirname(os.path.abspath(__file__))
        html_path = os.path.join(current_dir, 'project_assets', 'checkout.html')
        cls.html_url = f"file:///{html_path.replace(os.sep, '/')}"
    
    def setUp(self):
        """Set up before each test"""
        # Load the checkout page
        self.driver.get(self.html_url)
        time.sleep(1)  # Wait for page to load
    
    def test_valid_discount_code_save15(self):
        """
        Test Case: Apply valid discount code SAVE15
        
        Preconditions: Cart must have at least one item
        
        Test Steps:
        1. Add a product to cart
        2. Enter discount code 'SAVE15'
        3. Click 'Apply Discount' button
        4. Verify discount message appears
        5. Verify discount is calculated correctly (15% off)
        
        Expected Result:
        - Success message: "Discount code applied! 15% off your order."
        - Discount amount equals 15% of subtotal
        - Total is correctly calculated: subtotal - discount + shipping
        """
        
        # Step 1: Add product to cart
        add_to_cart_btn = self.wait.until(
            EC.element_to_be_clickable((By.ID, "add-product-1"))
        )
        add_to_cart_btn.click()
        time.sleep(0.5)
        
        # Verify product was added
        cart_items = self.driver.find_elements(By.CLASS_NAME, "cart-item")
        self.assertGreater(len(cart_items), 0, "Product should be added to cart")
        
        # Get initial subtotal
        subtotal_element = self.driver.find_element(By.ID, "subtotal")
        subtotal_text = subtotal_element.text.replace("$", "").replace(",", "")
        subtotal = float(subtotal_text)
        
        # Step 2: Enter discount code
        discount_input = self.driver.find_element(By.ID, "discount-code")
        discount_input.clear()
        discount_input.send_keys("SAVE15")
        
        # Step 3: Click Apply Discount button
        apply_btn = self.driver.find_element(By.ID, "apply-discount-btn")
        apply_btn.click()
        time.sleep(0.5)
        
        # Step 4: Verify success message
        discount_message = self.driver.find_element(By.ID, "discount-message")
        self.assertIn(
            "Discount code applied",
            discount_message.text,
            "Success message should appear"
        )
        self.assertIn(
            "15% off",
            discount_message.text,
            "Message should mention 15% off"
        )
        
        # Step 5: Verify discount calculation
        discount_element = self.driver.find_element(By.ID, "discount-amount")
        discount_text = discount_element.text.replace("-$", "").replace("$", "").replace(",", "")
        discount_amount = float(discount_text)
        
        expected_discount = round(subtotal * 0.15, 2)
        self.assertAlmostEqual(
            discount_amount,
            expected_discount,
            places=2,
            msg=f"Discount should be 15% of subtotal ({expected_discount})"
        )
        
        # Verify total calculation
        shipping_element = self.driver.find_element(By.ID, "shipping-cost")
        shipping_text = shipping_element.text.replace("$", "").replace(",", "")
        shipping_cost = float(shipping_text)
        
        total_element = self.driver.find_element(By.ID, "total-price")
        total_text = total_element.text.replace("$", "").replace(",", "")
        actual_total = float(total_text)
        
        expected_total = round(subtotal - discount_amount + shipping_cost, 2)
        self.assertAlmostEqual(
            actual_total,
            expected_total,
            places=2,
            msg=f"Total should be {expected_total}"
        )
        
        print(f"\n✓ Test passed!")
        print(f"  Subtotal: ${subtotal:.2f}")
        print(f"  Discount (15%): ${discount_amount:.2f}")
        print(f"  Shipping: ${shipping_cost:.2f}")
        print(f"  Total: ${actual_total:.2f}")
    
    def test_invalid_discount_code(self):
        """
        Test Case: Apply invalid discount code
        
        Test Steps:
        1. Add a product to cart
        2. Enter invalid discount code 'INVALID123'
        3. Click 'Apply Discount' button
        4. Verify error message appears
        5. Verify no discount is applied
        
        Expected Result:
        - Error message: "Invalid discount code."
        - Discount amount remains $0.00
        """
        
        # Step 1: Add product to cart
        add_to_cart_btn = self.wait.until(
            EC.element_to_be_clickable((By.ID, "add-product-2"))
        )
        add_to_cart_btn.click()
        time.sleep(0.5)
        
        # Step 2: Enter invalid discount code
        discount_input = self.driver.find_element(By.ID, "discount-code")
        discount_input.clear()
        discount_input.send_keys("INVALID123")
        
        # Step 3: Click Apply Discount button
        apply_btn = self.driver.find_element(By.ID, "apply-discount-btn")
        apply_btn.click()
        time.sleep(0.5)
        
        # Step 4: Verify error message
        discount_message = self.driver.find_element(By.ID, "discount-message")
        self.assertIn(
            "Invalid discount code",
            discount_message.text,
            "Error message should appear"
        )
        
        # Step 5: Verify no discount applied
        discount_element = self.driver.find_element(By.ID, "discount-amount")
        discount_text = discount_element.text.replace("-$", "").replace("$", "")
        discount_amount = float(discount_text)
        
        self.assertEqual(
            discount_amount,
            0.00,
            "No discount should be applied for invalid code"
        )
        
        print(f"\n✓ Test passed!")
        print(f"  Invalid code rejected correctly")
        print(f"  Discount: ${discount_amount:.2f}")
    
    def test_case_insensitive_discount_code(self):
        """
        Test Case: Verify discount code is case-insensitive
        
        Test Steps:
        1. Add a product to cart
        2. Enter discount code in lowercase 'save15'
        3. Click 'Apply Discount' button
        4. Verify discount is applied successfully
        
        Expected Result:
        - Discount code 'save15' should work same as 'SAVE15'
        - 15% discount applied
        """
        
        # Step 1: Add product to cart
        add_to_cart_btn = self.wait.until(
            EC.element_to_be_clickable((By.ID, "add-product-3"))
        )
        add_to_cart_btn.click()
        time.sleep(0.5)
        
        # Get subtotal
        subtotal_element = self.driver.find_element(By.ID, "subtotal")
        subtotal_text = subtotal_element.text.replace("$", "")
        subtotal = float(subtotal_text)
        
        # Step 2: Enter lowercase discount code
        discount_input = self.driver.find_element(By.ID, "discount-code")
        discount_input.clear()
        discount_input.send_keys("save15")
        
        # Step 3: Click Apply Discount button
        apply_btn = self.driver.find_element(By.ID, "apply-discount-btn")
        apply_btn.click()
        time.sleep(0.5)
        
        # Step 4: Verify discount applied
        discount_message = self.driver.find_element(By.ID, "discount-message")
        self.assertIn(
            "Discount code applied",
            discount_message.text,
            "Lowercase code should work"
        )
        
        discount_element = self.driver.find_element(By.ID, "discount-amount")
        discount_text = discount_element.text.replace("-$", "").replace("$", "")
        discount_amount = float(discount_text)
        
        expected_discount = round(subtotal * 0.15, 2)
        self.assertAlmostEqual(
            discount_amount,
            expected_discount,
            places=2,
            msg="15% discount should be applied"
        )
        
        print(f"\n✓ Test passed!")
        print(f"  Case-insensitive validation working")
        print(f"  Discount applied: ${discount_amount:.2f}")
    
    @classmethod
    def tearDownClass(cls):
        """Clean up after all tests"""
        time.sleep(2)  # Brief pause to see results
        cls.driver.quit()


if __name__ == "__main__":
    # Run tests with verbose output
    unittest.main(verbosity=2)
